import json
import os
import re
import sys
from http.server import BaseHTTPRequestHandler

try:
    import gspread
    from google.oauth2.service_account import Credentials
    GSPREAD_AVAILABLE = True
except ImportError:
    GSPREAD_AVAILABLE = False

# Add root directory to import modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def _extract_id(value):
    if not value:
        return None
    value = value.strip()
    if not value:
        return None
    m = re.search(r'/d/([a-zA-Z0-9_-]+)', value)
    if m:
        return m.group(1)
    m = re.search(r'/folders/([a-zA-Z0-9_-]+)', value)
    if m:
        return m.group(1)
    if re.match(r'^[a-zA-Z0-9_-]{10,}$', value):
        return value
    return value

class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        content_length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_length)
        payload = json.loads(post_data.decode('utf-8'))
        
        csv_rows = payload.get("rows", [])
        raw_folder = payload.get("folder_id")
        raw_spreadsheet = payload.get("spreadsheet_id")
        
        folder_id = _extract_id(raw_folder)
        spreadsheet_id = _extract_id(raw_spreadsheet)
        
        try:
            if not GSPREAD_AVAILABLE:
                raise Exception("gspread library is not installed.")
                
            # If deploying on Vercel, it is recommended to use environment variables for secrets.
            # But the existing logic expects credentials.json in the same folder.
            # On Vercel, the credentials.json should be in the deployment directory.
            # We first check if it exists in the root of the project.
            
            root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            creds_path = os.path.join(root_dir, 'credentials.json')
            
            if not os.path.exists(creds_path):
                # Fallback: check if it's set as an environment variable (for better security)
                creds_json_content = os.environ.get('GOOGLE_CREDENTIALS_JSON')
                if creds_json_content:
                    # Parse from environment variable
                    creds_info = json.loads(creds_json_content)
                    scopes = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']
                    credentials = Credentials.from_service_account_info(creds_info, scopes=scopes)
                else:
                    raise Exception("Missing credentials.json for Google Sheets API authentication.")
            else:
                scopes = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']
                credentials = Credentials.from_service_account_file(creds_path, scopes=scopes)
            
            gc = gspread.authorize(credentials)
            
            if spreadsheet_id:
                try:
                    sh = gc.open_by_key(spreadsheet_id)
                except gspread.exceptions.APIError as e:
                    body = str(e).lower()
                    if "invalid" in body and "argument" in body:
                        raise Exception(f"The ID ('{spreadsheet_id}') is not a valid Spreadsheet ID.")
                    raise e
            else:
                try:
                    sh = gc.create("University Timetable (Generated by GA)", folder_id=folder_id)
                except gspread.exceptions.APIError as e:
                    if "quota" in str(e).lower():
                        raise Exception("Google Drive storage quota exceeded.")
                    raise e
            
            if not spreadsheet_id:
                sh.share(None, role='reader', type='anyone')
            
            worksheet = sh.get_worksheet(0)
            if csv_rows:
                if spreadsheet_id:
                    worksheet.clear()
                worksheet.update(values=csv_rows, range_name=f'A1')
            
            # ─── PROFESSIONAL FORMATTING ─────────────────────────
            num_rows = len(csv_rows)
            num_cols = len(csv_rows[0]) if num_rows > 0 else 1
            col_letter = chr(ord('A') + num_cols - 1)
            
            # 1. Bold all headers and center everything
            worksheet.format(f"A1:{col_letter}{num_rows}", {
                "horizontalAlignment": "CENTER",
                "verticalAlignment": "MIDDLE",
                "textFormat": {"fontSize": 10},
            })
            
            # 2. Find and highlight "════" title rows and "Time" header rows
            for i, row in enumerate(csv_rows):
                row_idx = i + 1
                first_cell = str(row[0]) if row else ""
                
                if "══" in first_cell:
                    # Title row: Navy background, white bold text
                    worksheet.format(f"A{row_idx}:{col_letter}{row_idx}", {
                        "backgroundColor": {"red": 0.1, "green": 0.1, "blue": 0.4},
                        "textFormat": {"foregroundColor": {"red": 1, "green": 1, "blue": 1}, "bold": True, "fontSize": 11}
                    })
                elif first_cell == "Time":
                    # Header row: Light grey background, bold text
                    worksheet.format(f"A{row_idx}:{col_letter}{row_idx}", {
                        "backgroundColor": {"red": 0.9, "green": 0.9, "blue": 0.9},
                        "textFormat": {"bold": True}
                    })
                elif row_idx % 2 == 0:
                    # Alternating row colors (Zebra stripes)
                    worksheet.format(f"A{row_idx}:{col_letter}{row_idx}", {
                        "backgroundColor": {"red": 0.97, "green": 0.98, "blue": 1.0}
                    })

            response_data = {"url": sh.url}
            self.send_response(200)
            self.send_header("Header-name", "value")
            self.send_header('Content-type', 'application/json')
            self.send_header('Access-Control-Allow-Origin', '*')
            self.end_headers()
            self.wfile.write(json.dumps(response_data).encode("utf-8"))
            
        except Exception as e:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"error": str(e)}).encode("utf-8"))
